include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - avoid_function_literals_in_foreach_calls
    - prefer_final_locals
    - prefer_final_fields
    - prefer_single_quotes
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - unnecessary_this
    - use_super_parameters
    - avoid_redundant_argument_values
    - omit_local_variable_types
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - avoid_classes_with_only_static_members
    - require_trailing_commas
    - lines_longer_than_80_chars
    - directives_ordering

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/injection.config.dart"
    - "**/generated_plugin_registrant.dart" # Flutter plugin files
    - "**/firebase_options.dart" # Firebase config
    - "build/**"
    - ".dart_tool/**"
    - ".idea/**"
    - ".vscode/**"
    - "ios/**"
    - "android/**"

  errors:
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    prefer_relative_imports: ignore
    always_use_package_imports: error
    inference_failure_on_function_invocation: ignore
    inference_failure_on_instance_creation: ignore
    strict_raw_type: ignore
    one_member_abstracts: ignore
    flutter_style_todos: ignore

coverage:
  ignore:
    - "**/*.g.dart"
    - "**/freezed.dart"
    - "**/config.dart"
