name: pami
description: "PAMI is a location-based social interaction app designed to help users connect in real life through temporary shout-outs. Users can broadcast their availability, interests, or requests, allowing nearby users to engage and interact in a meaningful way. The app emphasizes spontaneity, safety, and ease of use while fostering real-world connections."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  auth_buttons: ^3.0.3
  auto_route: ^9.3.0+1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  fake_cloud_firestore: ^3.1.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.4.4
  geoflutterfire_plus: ^0.0.32
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  google_sign_in_mocks: ^0.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mock_exceptions: ^0.8.2
  mockito: ^5.4.5
  mocktail: ^1.0.4
  path: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  sign_in_with_apple: ^6.1.4
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_test: ^10.0.0
  build_runner:
  coverage: ^1.11.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
