name: pami
description: "PAMI is a location-based social interaction app designed to help users connect in real life through temporary shout-outs. Users can broadcast their availability, interests, or requests, allowing nearby users to engage and interact in a meaningful way. The app emphasizes spontaneity, safety, and ease of use while fostering real-world connections."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.3.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: any
  provider: ^6.1.2

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
