name: pami
description: "PAMI is a location-based social interaction app designed to help users connect in real life through temporary shout-outs. Users can broadcast their availability, interests, or requests, allowing nearby users to engage and interact in a meaningful way. The app emphasizes spontaneity, safety, and ease of use while fostering real-world connections."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  another_flushbar: ^1.12.30
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.3.0
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.1.0
  geoflutterfire_plus: ^0.0.32
  geolocator: ^14.0.2
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.3
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  logger: ^2.6.0
  path: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  sign_in_with_apple: ^7.0.1
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner:
  coverage: ^1.15.0
  fake_cloud_firestore: ^3.1.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  google_sign_in_mocks: ^0.3.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mock_exceptions: ^0.8.2
  mockito: ^5.4.6
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/markers/